### ISSUE TITLE
流程图预览没有显示内容

### ISSUE THREAD

**Issue by cmdares** [yimiyisu/kooteam#1]
1、新建流程图
2、编辑后ctrl+s保存
3、点击“预览”没有显示内容

**Comment by yimiyisu** [comment]
流程图是自动保存的，点击预览按钮，返回按钮，关闭窗口时都会触发保存

**Comment by cmdares** [comment]
测试目前版本发现有bug，您复测下，看看是否存在issue描述的问题

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yimiyisu** [comment]
> 测试目前版本发现有bug，您复测下，看看是否存在issue描述的问题
> 
> Sent with [GitHawk](http://githawk.com)

这个问题早上修复了，清一下浏览器缓存看看

**Comment by cmdares** [comment]
>> 测试目前版本发现有bug，您复测下，看看是否存在issue描述的问题 ...

@yimiyisu OK，我试下，感谢。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
