### ISSUE TITLE
项目卡片面板优化

### ISSUE THREAD

**Issue by cmdares** [yimiyisu/kooteam#10]
建议：
1、增加切换功能，支持列表模式和卡片模式的切换。
2、上方增加检索条件和排序条件，如果项目较多，比如几百个的话，多条件检索和排序的功能相对就重要了。
3、是否可以针对不同级别的权限看到的项目的条数不同，比如集团的领导能够查看所有公司，所有团队的任务呢？
1，2是平台能力的提升，相对容易修改。
3，属于业务场景的问题，建议考虑，看看是否实现。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yimiyisu** [comment]
1,2两点的优化，已经在进行，预计下周发布。对了，有好的建议可以加微信kooteam002直接提给我
