### ISSUE TITLE
完善用户体系

### ISSUE THREAD

**Issue by cmdares** [yimiyisu/kooteam#5]
1、完善基本的用户属性：
用户名
昵称
性别
单位
部门
职务
联系电话
电子邮箱
头像（可上传和修改）
微信二维码、钉钉二维码（可上传和修改）——便于手机扫描
备注
添加用户需要开启以上字段的的编辑功能，
2、用户登陆后，提供自己修改个人信息的功能
3、项目成员的选择列表中，增加必要的字段，如：单位、部门、职务
4、在任务中点击成员头像，可以显示成员基本信息

**Comment by yimiyisu** [comment]
私有部署版本用户体系跟钉钉，企业微信还有LADP都打通的，saas版本目前是接入个人微信的
