### ISSUE TITLE
创新思路：项目看板增加脑图模式

### ISSUE THREAD

**Issue by cmdares** [yimiyisu/kooteam#6]
系统当前已经提供项目看板，结构可以理解为：
项目
........ 分类
...................任务
...........................子任务
的多层结构，如果项目复杂度较高，环节和任务较多，能否考虑将项目内容结构，切换到脑图模式，以图形化展示，中心节点为“项目名称”,根据层级展开分类、任务、子任务。通过脑图的模式进行编辑，如点击一个任务节点，可以弹出对应的任务；同时，在脑图增加的任务节点可以生成任务内容，并在看板中显示，构成双向交互。

**Comment by yimiyisu** [comment]
这个思路非常赞，我先记录下来
