### ISSUE TITLE
优化任务相关功能

### ISSUE THREAD

**Issue by cmdares** [yimiyisu/kooteam#8]
”统计“功能
1、点击统计，上方显示，项目整体情况：任务总数、参与人数、历时时长（小时、天）
2、表格默认显示所有任务，默认时间正序显示
3、表格显示字段：任务分类、任务名称、创建时间、任务状态、负责人

项目卡片建议增加相关统计，更为直观：
增加：”任务历时15天“
"成员管理" 修改成： ”成员3人“

**Comment by yimiyisu** [comment]
表格显示已经在计划中，统计功能的建议非常好，tks
